"""Initial schema migration

Revision ID: 075e729fe537
Revises: 
Create Date: 2026-07-26 00:51:05.267103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075e729fe537'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('complementary_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('traditional_use', sa.Text(), nullable=True),
    sa.Column('possible_benefits', sa.JSON(), nullable=True),
    sa.Column('possible_risks', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('drug_interactions', sa.JSON(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise_library',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_area', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('stop_conditions', sa.JSON(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guideline_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('brand_names', sa.JSON(), nullable=True),
    sa.Column('normalized_code', sa.String(length=100), nullable=True),
    sa.Column('medicine_class', sa.String(length=150), nullable=True),
    sa.Column('otc_or_prescription', sa.String(length=50), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('side_effects', sa.JSON(), nullable=True),
    sa.Column('interaction_metadata', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generic_name')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex_at_birth', sa.String(length=50), nullable=True),
    sa.Column('gender_identity', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('professional_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('professional_type', sa.String(length=100), nullable=False),
    sa.Column('speciality', sa.String(length=150), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('professional_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('substance_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_code', sa.String(length=100), nullable=True),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_type', sa.String(length=100), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_mode', sa.String(length=50), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('main_complaint', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('condition_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_code', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=150), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prescribed_by', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_by_model', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('professional_review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('intake_session_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('generated_content', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_session_id', sa.String(length=36), nullable=False),
    sa.Column('question_code', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('patient_confirmed', sa.Boolean(), nullable=False),
    sa.Column('professional_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_session_id', sa.String(length=36), nullable=False),
    sa.Column('urgency_level', sa.String(length=50), nullable=False),
    sa.Column('decision_source', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('recommendations_blocked', sa.Boolean(), nullable=False),
    sa.Column('requires_professional_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_session_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_name', sa.String(length=150), nullable=False),
    sa.Column('normalized_code', sa.String(length=100), nullable=True),
    sa.Column('body_location', sa.String(length=150), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('onset_at', sa.DateTime(), nullable=True),
    sa.Column('duration_text', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plan_complementary_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_plan_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['complementary_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plan_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_plan_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plan_medication_information',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_plan_id', sa.String(length=36), nullable=False),
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('professional_review_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_catalog.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('input_mode', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confirmed_by_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['intake_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('red_flag_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('safety_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['safety_assessment_id'], ['safety_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('red_flag_events')
    op.drop_table('intake_answers')
    op.drop_table('care_plan_medication_information')
    op.drop_table('care_plan_exercises')
    op.drop_table('care_plan_complementary_options')
    op.drop_table('symptoms')
    op.drop_table('safety_assessments')
    op.drop_table('ocr_results')
    op.drop_table('intake_questions')
    op.drop_table('generated_reports')
    op.drop_table('care_plans')
    op.drop_table('uploaded_documents')
    op.drop_table('patient_medications')
    op.drop_table('patient_conditions')
    op.drop_table('intake_sessions')
    op.drop_table('consents')
    op.drop_table('appointments')
    op.drop_table('allergies')
    op.drop_table('professional_reviews')
    op.drop_table('professional_profiles')
    op.drop_table('patient_profiles')
    op.drop_table('medication_catalog')
    op.drop_table('guideline_chunks')
    op.drop_table('exercise_library')
    op.drop_table('complementary_options')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
